{% set name = "r-permute" %}
{% set version = "0.9-5" %}

package:
  name: {{ name|lower }}
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/permute_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/permute/permute_{{ version }}.tar.gz
  sha256: d2885384a07497e8df273689d6713fc7c57a7c161f6935f3572015e16ab94865

build:
  noarch: generic
  number: 3
  script: R CMD INSTALL --build .
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('permute')"  # [not win]
    - "\"%R%\" -e \"library('permute')\""  # [win]

about:
  home: https://github.com/gavinsimpson/permute
  license: GPL 2
  summary: 'Restricted permutations with R'
  description: |
    A set of restricted permutation designs for freely exchangeable, line transects (time series), and spatial
    grid designs plus permutation of blocks (groups of samples) is provided. 'permute' also allows split-plot designs,
    in which the whole-plots or split-plots or both can be freely-exchangeable or one of the restricted designs. The
    'permute' package is modelled after the permutation schemes of 'Canoco 3.1' (and later) by Cajo ter Braak.
  doc_url: https://cran.r-project.org/web/packages/permute/permute.pdf
  license_family: GPL2
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r
    - daf
    - ocefpaf
