appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: PTtXCyTmTpwHubKmy0eMVVZDn6Vx9oSxxe7ms7DGvIXcebE51qH5zdgVo232oyVe33mIJ9DMqJdBT0y3zh2GMGXDmbgmjITlAWiVGP0rn9LANV3PHi4GlKdYZN7yJAWtRheQdRLZBo8bLmssjrzaywTMnof8sjWW6i4+U2wkBxE02E1bGtNwyIaMPGFElC2iNoZA+leluw55L16bZkLmFMm0EG2bGoUT3mPGRwk9nSugw7QW4RCI6gJeNIDRO8c2V6JS/89vH7gRXDzsH/tukUCcIaCM3EXoZaKrgcl9PodXbsoWRpluNBkvdAXAdBYu8z4aL4L7OBB/Ro4DiGtohHiTa/BTvYD25KatamCpfza4YcA/Uf8p6YlnThwgx2mO9d5uKW2KFSLas5+xTRBNN2ln7sthtvdtZOU2xQb5qqlzSFKv28CMk23hUW6Y6iRbbM2fgxppF6szIgPxbr/jGlxRhqBEn/gZRj/4zlD8CDzrqj4WsysfcpgCxTmc91hOCIl4O9m9bBO+Tq6K6Kw00DsGt1+KhO/oVVMx9KJ3kXfExYj5o8s2jafEfuvZcgXB7qvFwpTtf33dlTU/XdQW4lbAF1hAAktvt+5Ijt0uq9lFGWBplZarzsIZzww/KpOhahiqOo+43eJMBUO6g7nLLU7dbysiNrJgp9Iod9ocpUw=}
